name: Publish labs
on:
  push:
    branches:
      - master
    paths:
      - '*/*/README.md'
jobs:
  publish_labs:
    runs-on: ubuntu-20.04
    env:
      USERNAME: ${{ secrets.PP_BOT_USERNAME }}
      PASSWORD: ${{ secrets.PP_BOT_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          - fetch-depth: 2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Update labs
        run: |
          ./scripts/update-ocw.sh
